### ISSUE TITLE
🧑‍💻 Add Extra important Details in README File

### ISSUE THREAD

**Issue by Suryansh1720001** [antrikshmisri/checkpoint#42]
Hello @RyanWalker277 

**Is your feature request related to a problem? Please describe.**
### Features that I want to add in README File

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in readme file

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by Suryansh1720001** [comment]
@antrikshmisri 
Any Update?

**Comment by antrikshmisri** [comment]
Hey @Suryansh1720001, thank you for opening this issue. These details were initially planned to go in the project's website. But due to some other work, the website creation got deprioritized. Hence, you can go ahead with formatting work in `README`. For other changes, we will have to wait for the website development to finish. Thanks!
